#include <vector>

#include "datatypes.h"

Scope initialize_globals() {
  return Scope{{"+",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_int,
                }},
               {"-",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_int,
                }},
               {"*",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_int,
                }},
               {"/",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_int,
                }},
               {"%",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_int,
                }},
               {"<",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_bool,
                }},
               {"<=",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_bool,
                }},
               {">",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_bool,
                }},
               {">=",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                    C_type::C_bool,
                }},
               {"and",
                FnType{
                    C_type::C_bool,
                    C_type::C_bool,
                    C_type::C_bool,
                }},
               {"or",
                FnType{
                    C_type::C_bool,
                    C_type::C_bool,
                    C_type::C_bool,
                }},
               {"=",
                FnType{
                    C_type::C_any,
                    C_type::C_any,
                }},
               {"unary_-",
                FnType{
                    C_type::C_int,
                    C_type::C_int,
                }},
               {"unary_not", FnType{
                                 C_type::C_bool,
                                 C_type::C_bool,
                             }}};
}
