// #include "symtab.h"
// #include "datatypes.h"

// static const TS_Scope kTypecheckGlobals{
//     {"+",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_int,
//      }},
//     {"-",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_int,
//      }},
//     {"*",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_int,
//      }},
//     {"/",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_int,
//      }},
//     {"%",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_int,
//      }},
//     {"<",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_bool,
//      }},
//     {"<=",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_bool,
//      }},
//     {">",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_bool,
//      }},
//     {">=",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//          C_type::C_bool,
//      }},
//     {"and",
//      FnType{
//          C_type::C_bool,
//          C_type::C_bool,
//          C_type::C_bool,
//      }},
//     {"or",
//      FnType{
//          C_type::C_bool,
//          C_type::C_bool,
//          C_type::C_bool,
//      }},
//     {"unary_-",
//      FnType{
//          C_type::C_int,
//          C_type::C_int,
//      }},
//     {"unary_not",
//      FnType{
//          C_type::C_bool,
//          C_type::C_bool,
//      }},
//     {"print_int",
//      FnType{
//          C_type::C_int,
//          C_type::C_unit,
//      }},
//     {"print_bool",
//      FnType{
//          C_type::C_bool,
//          C_type::C_unit,
//      }},
//     {"read_int",
//      FnType{
//          C_type::C_int,
//      }},
// };
